site_dir: '../cppmap.github.io'

# Project information
site_name: C++ の歩き方 | CppMap
site_description: C++17, C++20, C++23, C++26 に関する情報を調査・提供します
site_author: Ryo Suzuki

# Repository
repo_name: cppmap/cppmap.docs
repo_url: https://github.com/cppmap/cppmap.docs
edit_uri: ""

# Copyright
copyright: To the extent possible under law, Ryo Suzuki has waived all copyright and related or neighboring rights to C++ の歩き方 | CppMap. Third party copyrights are property of their respective owners.

# Theme
theme:
  name: 'material'
  language: 'ja'
  favicon: 'assets/images/logo.png'
  logo:
    icon: 'donut_small'  
  palette:
    primary: 'teal'
    accent: 'teal'  
  feature:
    tabs: true
extra:
  search:
    language: 'jp'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.magiclink
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - cppmap_styles.css

# Page tree
nav:
  - Home: index.md
  - C++ 規格:
    - 標準化会議: standardization/meetings.md
  - 学習:
    - オンライン資料: learn/online-resources.md
    - 国内の勉強会: learn/studymeetings.md
  - ツール:
    - オンラインコンパイラ: tools/onlinecompilers.md
